spring:
  application:
    name: myhome-api
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/myhome
    username: myhome
    password: RjpXGtp6dFaDv2vpaMJd

server:
  port: 9090

graphql:
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: true

graphiql:
  mapping: /graphiql
  endpoint: /graphql
  enabled: true